# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "39 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-12
      CXX: g++-12
    environment: monitor_env

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install meson g++-12 ninja-build libprotobuf-dev protobuf-compiler libcurl4-openssl-dev

      # Runs a set of commands using the runners shell
      - name: Configure
        run: meson setup --warnlevel 3 --buildtype release _build

      - name: Compile
        run: ninja -C _build

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false

      - name: Run
        env:
          JNC_USERNAME: ${{ secrets.JNC_USERNAME }}
          JNC_PASSWORD: ${{ secrets.JNC_PASSWORD }}
        run: _build/src/aoab-monitor > updates.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Auto-update
          file_pattern: updates.json latest.html
          branch: gh-pages

      - name: Email
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          # email subject
          subject: 'AOAB-Monitor: epub update'
          # email body as text
          body: ${{ github.repository }} sees an update. https://aoabmonitor.talinet.net/latest.html
          # comma-separated string, send email to
          to: ${{ secrets.NOTIFY_EMAIL }}
          # from email name
          from: talisein
