# This is a basic workflow to help you get started with Actions

name: Weekly Stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "15 21 * 3-10 1"
  - cron: "5 22 * 11,12,1,2,3 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-12
      CXX: g++-12
    environment: monitor_env

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo add-apt-repository -n ppa:talisein/libxml++5.0
          sudo add-apt-repository -n ppa:talisein/libboost-ext-ut
          sudo apt-get update
          sudo apt-get install meson g++-12 ninja-build libprotobuf-dev protobuf-compiler libcurl4-openssl-dev libxml2-dev gnuplot-nox libhowardhinnant-date-dev libxml++5.0-dev libboost-ext-ut-dev

      # Runs a set of commands using the runners shell
      - name: Configure
        run: meson setup --warnlevel 3 --buildtype release _build

      - name: Compile
        run: ninja -C _build

      - name: Run
        env:
          JNC_USERNAME: ${{ secrets.JNC_USERNAME }}
          JNC_PASSWORD: ${{ secrets.JNC_PASSWORD }}
        run: |
          mkdir plotdata
          _build/src/weekly/partget data/word_stats.csv data/word_stats.csv plotdata/
          cp data/word_stats.csv plotdata/
          cd plotdata
          gnuplot ../histo.plt > plot.png
          gnuplot ../projection.plt > projection.png
          cd ..

      - name: Save .dat
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: gnuplot_dats
          path: |
            plotdata/*
          if-no-files-found: ignore
          retention-days: 7

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-main-action
        with:
          commit_message: Auto-update
          file_pattern: data/word_stats.csv
          branch: main

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false

      - name: Make pages
        run: |
          cp plotdata/plot.png stats/plot.png
          cp plotdata/projection.png stats/projection.png
          cp plotdata/word_stats.csv stats/word_stats.csv

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Auto-update
          file_pattern: stats/plot.png stats/projection.png stats/word_stats.csv
          branch: gh-pages
